import type { Config } from "tailwindcss";

const config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Use CSS variables for Tailwind color system
        neutral: {
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          1000: "var(--color-neutral-1000)",
        },
        primary: {
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "#DC5696",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          1000: "var(--color-primary-1000)",
        },
        info: {
          100: "var(--alert-info-100)",
          200: "var(--alert-info-200)",
          300: "var(--alert-info-300)",
          400: "var(--alert-info-400)",
          500: "var(--alert-info-500)",
          600: "var(--alert-info-600)",
          700: "var(--alert-info-700)",
          800: "var(--alert-info-800)",
          900: "var(--alert-info-900)",
          1000: "var(--alert-info-1000)",
        },
        success: {
          100: "var(--alert-success-100)",
          200: "var(--alert-success-200)",
          300: "var(--alert-success-300)",
          400: "var(--alert-success-400)",
          500: "var(--alert-success-500)",
          600: "var(--alert-success-600)",
          700: "var(--alert-success-700)",
          800: "var(--alert-success-800)",
          900: "var(--alert-success-900)",
          1000: "var(--alert-success-1000)",
        },
        warning: {
          100: "var(--alert-warning-100)",
          200: "var(--alert-warning-200)",
          300: "var(--alert-warning-300)",
          400: "var(--alert-warning-400)",
          500: "var(--alert-warning-500)",
          600: "var(--alert-warning-600)",
          700: "var(--alert-warning-700)",
          800: "var(--alert-warning-800)",
          900: "var(--alert-warning-900)",
          1000: "var(--alert-warning-1000)",
        },
        danger: {
          100: "var(--alert-danger-100)",
          200: "var(--alert-danger-200)",
          300: "var(--alert-danger-300)",
          400: "var(--alert-danger-400)",
          500: "var(--alert-danger-500)",
          600: "var(--alert-danger-600)",
          700: "var(--alert-danger-700)",
          800: "var(--alert-danger-800)",
          900: "var(--alert-danger-900)",
          1000: "var(--alert-danger-1000)",
        },
      },
      spacing: {
        "3xs": "var(--spacing-3xs)",
        "2xs": "var(--spacing-2xs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        md: "var(--font-size-md)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",

        "3xs-fluid": "var(--font-size-3xs-fluid)",
        "2xs-fluid": "var(--font-size-2xs-fluid)",
        "xs-fluid": "var(--font-size-xs-fluid)",
        "sm-fluid": "var(--font-size-sm-fluid)",
        "md-fluid": "var(--font-size-md-fluid)",
        "lg-fluid": "var(--font-size-lg-fluid)",
        "xl-fluid": "var(--font-size-xl-fluid)",
        "2xl-fluid": "var(--font-size-2xl-fluid)",
        "3xl-fluid": "var(--font-size-3xl-fluid)",
        "4xl-fluid": "var(--font-size-4xl-fluid)",
        "5xl-fluid": "var(--font-size-5xl-fluid)",
        "6xl-fluid": "var(--font-size-6xl-fluid)",
        "7xl-fluid": "var(--font-size-7xl-fluid)",
        "8xl-fluid": "var(--font-size-8xl-fluid)",
      },
      fontWeight: {
        light: "var(--font-weight-300)",
        normal: "var(--font-weight-400)",
        medium: "var(--font-weight-500)",
        bold: "var(--font-weight-700)",
        "extra-bold": "var(--font-weight-800)",
      },
      lineHeight: {
        "3xs": "var(--line-height-3xs)",
        "2xs": "var(--line-height-2xs)",
        xs: "var(--line-height-xs)",
        sm: "var(--line-height-sm)",
        md: "var(--line-height-md)",
        lg: "var(--line-height-lg)",
        xl: "var(--line-height-xl)",
        "2xl": "var(--line-height-2xl)",
        "3xl": "var(--line-height-3xl)",
        "4xl": "var(--line-height-4xl)",
        "5xl": "var(--line-height-5xl)",
        "6xl": "var(--line-height-6xl)",
      },
      fontFamily: {
        punk: ["var(--font-family-punk)"],
        specialElite: ["var(--font-family-special-elite)"],
        cutMeOut1: ["var(--font-family-cutmeout1)"],
        cutMeOut2: ["var(--font-family-cutmeout2)"],
        cutMeOut3: ["var(--font-family-cutmeout3)"],
      },
      boxShadow: {
        sm: "var(--shadow-0_08)",
        md: "var(--shadow-0_16)",
        lg: "var(--shadow-0_24)",
        xl: "var(--shadow-0_32)",
      },
      borderRadius: {
        sm: "var(--shape-sm)",
        md: "var(--shape-md)",
        lg: "var(--shape-lg)",
        xl: "var(--shape-xl)",
      },
      borderWidth: {
        none: "0",
        sm: "var(--border-width-sm)",
        md: "var(--border-width-md)",
        lg: "var(--border-width-lg)",
        xl: "var(--border-width-xl)",
      },
    },
  },
  plugins: [],
  darkMode: "media",
} satisfies Config;

export default config;
