name: "Chromatic"

on:
  push:
    branches:
      - "*"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build Storybook
        run: npx nx build-storybook components
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: "dist/storybook/components"

    # Add a conditional statement to skip the job on 'main' and 'staging' branches
    # if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging' }}
