name: Process Figma Tokens PR
on: pull_request

jobs:
  run_if:
    if: ${{ github.head_ref == 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run style-dictionary
        run: npx nx build @mmhuntsberry/tokens

      - name: Run who am i
        run: |
          git config --global user.email "mmhuntsberry@gmail.com"
          git config --global user.name "mmhuntsberry"

      - name: Bump patch version and generate changelog
        id: version
        run: |
          cd packages/tokens
          npm install -g standard-version
          npm version patch --no-git-tag-version
          standard-version --skip.tag --infile CHANGELOG.md

      - name: extract version number
        run: |
          cd packages/tokens
          BUILD_VERSION=$(awk -F \" '$2 == "version" {print $4}' package.json)
          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - name: Get Recent Commits
        id: recent_commits
        run: |
          git log --pretty=format:"- %s (%h)" --no-merges -n 10 > recent_commits.txt

      - name: Save Recent Commits to Environment File
        run: |
          echo "RECENT_COMMITS=$(cat recent_commits.txt)" >> $GITHUB_ENV

      - name: Create Tag and Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: |
            Changes in this Release:
            ${{ env.RECENT_COMMITS }}
          draft: false
          prerelease: false
