name: Process Figma Tokens PR
on: pull_request

jobs:
  run_if:
    if: ${{ github.head_ref == 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run style-dictionary
        run: npx nx build @mmhuntsberry/tokens

      - name: Run who am i
        run: |
          git config --global user.email "mmhuntsberry@gmail.com"
          git config --global user.name "mmhuntsberry"

      - name: Bump patch version and generate changelog
        id: version
        run: |
          cd packages/tokens
          npm install -g standard-version
          npm version patch --no-git-tag-version
          standard-version --skip.tag --infile CHANGELOG.md

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Matthew Huntsberry
          author_email: mmhuntsberry@gmail.com
          message: "chore: style-dictionary output (version ${{ env.VERSION }})"
          add: "."
