name: Figma Tokens Sync

on:
  push:
    branches:
      - main

jobs:
  publish-tokens-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Build packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/figma-tokens'
        run: |
          npx nx run @mmhuntsberry/tokens:pack
          cd packages/tokens/dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
