# name: Pre Release Publish

# on:
#   push:
#     branches:
#       - staging

# jobs:
#   publish-components-gpr:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci

#       - name: Build packages and publish
#         run: |
#           npx nx build components
#           cd dist
#           npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
