name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

# env:
#   HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [16]
        npm-version: [8]
        yarn-version: ["1.22.x"]
        pnpm-version: [7]
    steps:
      # ... (existing steps omitted for brevity)

      - name: Install Dependencies
        run: npm install

      - name: Release
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx nx affected --target release --projects=tokens
