name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

# env:
#   HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run who am i
        run: |
          git config --global user.email "mmhuntsberry@gmail.com"
          git config --global user.name "mmhuntsberry"

      - name: Release
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_PR }}
          NPM_TOKEN: ${{ secrets.GH_PAT_PR }}
        run: |
          npx nx affected --target release --projects=tokens
